name: genie_luck
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rounded_date_picker: ^3.0.4
  go_router: ^14.8.1
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  result_dart: ^2.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  intl: ^0.20.2
  flutter_google_maps_webservices: ^1.1.1
  uuid: ^4.5.1
  intl_phone_field: ^3.1.0
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^3.13.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.3.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - lib/l10n/
