// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCLnnsEbLGYG36k9oBjCVRcSTACb4Xtww',
    appId: '1:100540346901:web:b118c778c11ceaecbd941c',
    messagingSenderId: '100540346901',
    projectId: 'genie-luck-dev',
    authDomain: 'genie-luck-dev.firebaseapp.com',
    storageBucket: 'genie-luck-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDHTMeqSsq28YMOc-QhuHgf6otvE55HRI',
    appId: '1:100540346901:android:ccbda1ae047ed794bd941c',
    messagingSenderId: '100540346901',
    projectId: 'genie-luck-dev',
    storageBucket: 'genie-luck-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPATmUS9y3m3RJlcHLCrgWFk7mu9uO57I',
    appId: '1:100540346901:ios:ab3b6294ae1a0a06bd941c',
    messagingSenderId: '100540346901',
    projectId: 'genie-luck-dev',
    storageBucket: 'genie-luck-dev.firebasestorage.app',
    iosBundleId: 'com.genieluck.dev',
  );
}
