// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU7SzYvTbFFw81IzXGFEC59iDyDqt4XnU',
    appId: '1:723162751270:web:76ec5d11bbf68fc0dbe1e7',
    messagingSenderId: '723162751270',
    projectId: 'genie-luck-stg',
    authDomain: 'genie-luck-stg.firebaseapp.com',
    storageBucket: 'genie-luck-stg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7STUOoOUl_vxEzH2EcXjWwHcGIWGvJnU',
    appId: '1:723162751270:android:9b3f24b62bf7a1e2dbe1e7',
    messagingSenderId: '723162751270',
    projectId: 'genie-luck-stg',
    storageBucket: 'genie-luck-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78-rnUxwOUa82zTLUylAg0JJAOTpzDXQ',
    appId: '1:723162751270:ios:1ca0164241d2b334dbe1e7',
    messagingSenderId: '723162751270',
    projectId: 'genie-luck-stg',
    storageBucket: 'genie-luck-stg.firebasestorage.app',
    iosBundleId: 'com.genieluck.stg',
  );
}
