// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxV-5FyTrvCEsQTW_tYRqO5KSAd0WD8v8',
    appId: '1:663290606209:web:c8a723ba6ed871651e9380',
    messagingSenderId: '663290606209',
    projectId: 'genie-luck-prd',
    authDomain: 'genie-luck-prd.firebaseapp.com',
    storageBucket: 'genie-luck-prd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyVaLYHFtXAC6zNACr6kkgfwRx0_BRfM',
    appId: '1:663290606209:android:0aa34beefde8b6e71e9380',
    messagingSenderId: '663290606209',
    projectId: 'genie-luck-prd',
    storageBucket: 'genie-luck-prd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkARR58m-N0BQx91cpsJD4ow016ns3jcM',
    appId: '1:663290606209:ios:ca2a64cdf0293df71e9380',
    messagingSenderId: '663290606209',
    projectId: 'genie-luck-prd',
    storageBucket: 'genie-luck-prd.firebasestorage.app',
    iosBundleId: 'com.genieluck.prd',
  );
}
